import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import SideBar from "@/components/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-1 text-gray-12 flex h-dvh flex-col">
        <Header />
        <SideBar />
        {children}
      </body>
    </html>
  );
}
